file_read = open("Codingal.txt","r")
print("file in read mode")
print(file_read.read())
file_read.close()
file_write = open("Codingal.txt","w")
print("file in write mode")
file_write.write("Hi my name is Ritvik")
file_write.close()
file_append = open("Codingal.txt","a")
print("file in append mode")
file_append.write("My hobbie is to do programming")
file_append.close()