file_read = open('Codingal.txt','r')
print("File in Read Mode -")
print(file_read.read())
file_read.close()
file_write = open('Codingal.txt','w')
file_write.write("File in write mode ...... ")
file_write.write("My age is 25 years")
file_write.close()
file_append = open('Codingal.txt','a')
file_append.write("\nFile in append mode .....")
file_append.write("This is append txt")
file_append.close()