file = open('Codingal.txt','r')
print(file.read())
file.close()
file = open('Codingal.txt','r')
print("\n Read first 8 characters \n")
file.close()
file = open('Codingal.txt','a')
file.write("Hi ! I am Ritvik and i am in 5th grade")
file.close()